server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/distancelearning-authuser
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      jdbc:
#        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect



